
// Objective-C API for talking to the following Go packages
//
//	goMobileSupport/src
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoMobileDemoApp_FRAMEWORK_H__
#define __GoMobileDemoApp_FRAMEWORK_H__

#include "Support.objc.h"
#include "Universe.objc.h"

#endif
